
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/HostX64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.41.34123.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/3.29.3/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\ems\\Lectron\\build\\Desktop_Qt_5_15_2_MSVC2019_64bit-Release\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-tl3j25"
      binary: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-tl3j25"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-tl3j25'
        
        Run Build Command(s): C:/msys64/mingw64/bin/ninja.exe -v cmTC_d2017
        [1/2] C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\HostX64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_d2017.dir\\CMakeCXXCompilerABI.cpp.obj /FdCMakeFiles\\cmTC_d2017.dir\\ /FS -c C:\\Qt\\Tools\\CMake_64\\share\\cmake-3.29\\Modules\\CMakeCXXCompilerABI.cpp
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_d2017.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_d2017.dir\\CMakeCXXCompilerABI.cpp.obj  /out:cmTC_d2017.exe /implib:cmTC_d2017.lib /pdb:cmTC_d2017.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/PROGRA~1/MICROS~3/2022/COMMUN~1/VC/Tools/MSVC/1441~1.341/bin/Hostx64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:210 (cmake_determine_linker_id)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Running the CXX compiler's linker: "C:/PROGRA~1/MICROS~3/2022/COMMUN~1/VC/Tools/MSVC/1441~1.341/bin/Hostx64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.41.34123.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/FindThreads.cmake:99 (CHECK_CXX_SOURCE_COMPILES)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementation-extras.cmake:67 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementationConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rcl/cmake/rclConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-x2zrta"
      binary: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-x2zrta"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "C:/opt/ros/foxy/x64/share/fastrtps_cmake_module/cmake/Modules"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: 'C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-x2zrta'
        
        Run Build Command(s): C:/msys64/mingw64/bin/ninja.exe -v cmTC_b31a0
        [1/2] C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\HostX64\\x64\\cl.exe  /nologo /TP -DCMAKE_HAVE_LIBC_PTHREAD  /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -std:c++14 -MDd /showIncludes /FoCMakeFiles\\cmTC_b31a0.dir\\src.cxx.obj /FdCMakeFiles\\cmTC_b31a0.dir\\ /FS -c C:\\ems\\Lectron\\build\\Desktop_Qt_5_15_2_MSVC2019_64bit-Release\\CMakeFiles\\CMakeScratch\\TryCompile-x2zrta\\src.cxx
        \x1b[31mFAILED: \x1b[0mCMakeFiles/cmTC_b31a0.dir/src.cxx.obj 
        C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\HostX64\\x64\\cl.exe  /nologo /TP -DCMAKE_HAVE_LIBC_PTHREAD  /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -std:c++14 -MDd /showIncludes /FoCMakeFiles\\cmTC_b31a0.dir\\src.cxx.obj /FdCMakeFiles\\cmTC_b31a0.dir\\ /FS -c C:\\ems\\Lectron\\build\\Desktop_Qt_5_15_2_MSVC2019_64bit-Release\\CMakeFiles\\CMakeScratch\\TryCompile-x2zrta\\src.cxx
        C:\\ems\\Lectron\\build\\Desktop_Qt_5_15_2_MSVC2019_64bit-Release\\CMakeFiles\\CMakeScratch\\TryCompile-x2zrta\\src.cxx(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CheckLibraryExists.cmake:69 (try_compile)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/FindThreads.cmake:112 (CHECK_LIBRARY_EXISTS)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/FindThreads.cmake:175 (_threads_check_lib)"
      - "C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementation-extras.cmake:67 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementationConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rcl/cmake/rclConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Looking for pthread_create in pthreads"
    directories:
      source: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-u63sis"
      binary: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-u63sis"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "C:/opt/ros/foxy/x64/share/fastrtps_cmake_module/cmake/Modules"
    buildResult:
      variable: "CMAKE_HAVE_PTHREADS_CREATE"
      cached: true
      stdout: |
        Change Dir: 'C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-u63sis'
        
        Run Build Command(s): C:/msys64/mingw64/bin/ninja.exe -v cmTC_588a9
        [1/2] C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\HostX64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR /EHsc -DCHECK_FUNCTION_EXISTS=pthread_create /Zi /Ob0 /Od /RTC1 -std:c++14 -MDd /showIncludes /FoCMakeFiles\\cmTC_588a9.dir\\CheckFunctionExists.cxx.obj /FdCMakeFiles\\cmTC_588a9.dir\\ /FS -c C:\\ems\\Lectron\\build\\Desktop_Qt_5_15_2_MSVC2019_64bit-Release\\CMakeFiles\\CMakeScratch\\TryCompile-u63sis\\CheckFunctionExists.cxx
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_588a9.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_588a9.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_588a9.exe /implib:cmTC_588a9.lib /pdb:cmTC_588a9.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthreads.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        \x1b[31mFAILED: \x1b[0mcmTC_588a9.exe 
        C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_588a9.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_588a9.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_588a9.exe /implib:cmTC_588a9.lib /pdb:cmTC_588a9.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthreads.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        LINK Pass 1: command "C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_588a9.dir\\CheckFunctionExists.cxx.obj /out:cmTC_588a9.exe /implib:cmTC_588a9.lib /pdb:cmTC_588a9.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console pthreads.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_588a9.dir/intermediate.manifest CMakeFiles\\cmTC_588a9.dir/manifest.res" failed (exit code 1104) with the following output:
        LINK : fatal error LNK1104: cannot open file 'pthreads.lib'\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/CheckLibraryExists.cmake:69 (try_compile)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/FindThreads.cmake:112 (CHECK_LIBRARY_EXISTS)"
      - "C:/Qt/Tools/CMake_64/share/cmake-3.29/Modules/FindThreads.cmake:176 (_threads_check_lib)"
      - "C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementation-extras.cmake:67 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rmw_implementation/cmake/rmw_implementationConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/rcl/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rcl/cmake/rclConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)"
      - "C:/opt/ros/foxy/x64/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)"
      - "C:/opt/ros/foxy/x64/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)"
      - "CMakeLists.txt:17 (find_package)"
    checks:
      - "Looking for pthread_create in pthread"
    directories:
      source: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-vzsgiq"
      binary: "C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-vzsgiq"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "C:/opt/ros/foxy/x64/share/fastrtps_cmake_module/cmake/Modules"
    buildResult:
      variable: "CMAKE_HAVE_PTHREAD_CREATE"
      cached: true
      stdout: |
        Change Dir: 'C:/ems/Lectron/build/Desktop_Qt_5_15_2_MSVC2019_64bit-Release/CMakeFiles/CMakeScratch/TryCompile-vzsgiq'
        
        Run Build Command(s): C:/msys64/mingw64/bin/ninja.exe -v cmTC_e524f
        [1/2] C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\HostX64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /GR /EHsc -DCHECK_FUNCTION_EXISTS=pthread_create /Zi /Ob0 /Od /RTC1 -std:c++14 -MDd /showIncludes /FoCMakeFiles\\cmTC_e524f.dir\\CheckFunctionExists.cxx.obj /FdCMakeFiles\\cmTC_e524f.dir\\ /FS -c C:\\ems\\Lectron\\build\\Desktop_Qt_5_15_2_MSVC2019_64bit-Release\\CMakeFiles\\CMakeScratch\\TryCompile-vzsgiq\\CheckFunctionExists.cxx
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_e524f.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_e524f.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_e524f.exe /implib:cmTC_e524f.lib /pdb:cmTC_e524f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthread.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        \x1b[31mFAILED: \x1b[0mcmTC_e524f.exe 
        C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Qt\\Tools\\CMake_64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_e524f.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_e524f.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_e524f.exe /implib:cmTC_e524f.lib /pdb:cmTC_e524f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthread.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        LINK Pass 1: command "C:\\PROGRA~1\\MICROS~3\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1441~1.341\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_e524f.dir\\CheckFunctionExists.cxx.obj /out:cmTC_e524f.exe /implib:cmTC_e524f.lib /pdb:cmTC_e524f.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console pthread.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_e524f.dir/intermediate.manifest CMakeFiles\\cmTC_e524f.dir/manifest.res" failed (exit code 1104) with the following output:
        LINK : fatal error LNK1104: cannot open file 'pthread.lib'\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
